apply_library_patches: true
base_image: null
build:
  arguments: {}
  model_server: TrussServer
bundled_packages_dir: packages
data_dir: data
description: Extract information from images of invoices
environment_variables: {}
examples_filename: examples.yaml
external_data: null
external_package_dirs: []
hf_cache: null
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata:
  avatar_url: https://cdn.baseten.co/production/static/explore/impira-logo.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/document-qa.png
  example_model_input:
    prompt: What is the invoice number?
    url: https://templates.invoicehome.com/invoice-template-us-neat-750px.png
  tags:
  - text-generation
model_module_dir: model
model_name: LayoutLM Document QA
model_type: custom
python_version: py39
requirements:
- Pillow==10.0.0
- pytesseract==0.3.10
- torch==2.0.1
- transformers==4.30.2
resources:
  accelerator: null
  cpu: '4'
  memory: 16Gi
  use_gpu: false
runtime:
  predict_concurrency: 1
secrets: {}
spec_version: '2.0'
system_packages:
- tesseract-ocr
train:
  resources:
    accelerator: null
    cpu: 500m
    memory: 512Mi
    use_gpu: false
  training_class_filename: train.py
  training_class_name: Train
  training_module_dir: train
  variables: {}
