base_image: null
bundled_packages_dir: packages
data_dir: data
description: Open source LLM.
environment_variables: {}
examples_filename: examples.yaml
external_package_dirs: []
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata:
  avatar_url: https://cdn.baseten.co/production/static/explore/wizard.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/wizardlm.png
  tags:
  - text-generation
model_module_dir: model
model_name: Falcon 7B Instruct
model_type: custom
python_version: py39
requirements:
- torch
- peft
- sentencepiece
- accelerate
- bitsandbytes
- einops
- git+https://github.com/huggingface/transformers.git
resources:
  cpu: "3"
  memory: 16Gi
  use_gpu: true
  accelerator: "A100:2"
secrets: {}
spec_version: '2.0'
system_packages: []