FROM ghcr.io/huggingface/text-generation-inference:3.2.0

ENV MODEL_ID="leon-se/Qwen2.5-VL-7B-Instruct-FP8-Dynamic"

# We previously downloaded the model files using the `download-model` script.
COPY data /data