name: Released Version checker
description: Checks if the current tag has already been deployed.
inputs:
  recipe-name:
    description: Targeted Recipe
    required: true
  version:
    description: Version Number of Recipe
    required: true
  repo-token:
    description: Github token
    required: true
outputs:
  IS_NEW:
    description: Whether the version number has already been released
    value: ${{ steps.check_new.outputs.IS_NEW }}

runs:
  using: "composite"
  steps:
    - name: Check for changes
      shell: bash
      id: check_new
      run: |
        
        tags=$(curl -L \
        --header 'authorization: Bearer ${{ inputs.repo-token }}' \
        --header 'content-type: application/json' \
        https://api.github.com/orgs/saladtechnologies/packages/container/recipe-${{ inputs.recipe-name }}/versions | jq -r 'try(.[0].metadata.container.tags | any(. == "${{ inputs.version }}") ) catch "false"')
        
        echo $tags
        
        # Checks to see if the specified version already exists in the packages versions
        if [ "$tags" == "false" ]; then
          echo "IS_NEW=true" >> $GITHUB_OUTPUT
          echo "It is new!!!"
        else
          echo "IS_NEW=false" >> $GITHUB_OUTPUT
          echo "This tag already exists."
        fi

