name: docker recipe
description: does docker stuff
inputs:
  recipe-name:
    description: targeted thing
    required: true
  version:
    description: version
    required: true
  repo-token:
    description: token
    required: true

runs:
  using: "composite"

  steps:
    # Check out the repo
    - name: Checkout repository
      uses: actions/checkout@v2

    # Log into GHCR
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.repo-token }}

    # Get meta data
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/saladtechnologies/recipe-${{ inputs.recipe-name }}:${{ inputs.version }}

    # Create and push image
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context:  ./src/${{ inputs.recipe-name }}
        file: ./src/${{ inputs.recipe-name }}/Dockerfile
        push: true
        tags: ghcr.io/saladtechnologies/recipe-${{ inputs.recipe-name }}:${{ inputs.version }}
        labels: ${{ steps.meta.outputs.labels }}
