FROM python:3.10-slim

RUN pip install --no-dependencies --no-cache-dir elastic_models[nvidia]==0.0.11 --index-url https://thestage.jfrog.io/artifactory/api/pypi/pypi-thestage-ai-production/simple --extra-index-url https://pypi.nvidia.com --extra-index-url https://pypi.org/simple \
&& pip install  --no-cache-dir qlip-serve==0.1.15 requests --extra-index-url https://thestage.jfrog.io/artifactory/api/pypi/pypi-thestage-ai-production/simple