apply_library_patches: true
base_image: null
build:
  arguments: {}
  model_server: TrussServer
bundled_packages_dir: packages
data_dir: data
description: StableLM is an open-source AI language model developed by StabilityAI
environment_variables: {}
examples_filename: examples.yaml
external_data: null
external_package_dirs: []
hf_cache: null
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata:
  avatar_url: https://cdn.baseten.co/production/static/explore/stability.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/stable-lm.png
  example_model_input:
    prompt: <|USER|>What's your mood today?<|ASSISTANT|>
  tags:
  - text-generation
model_module_dir: model
model_name: StableLM
model_type: custom
python_version: py38
requirements:
- torch==2.0.1
- peft==0.3.0
- sentencepiece==0.1.99
- accelerate==0.20.3
- bitsandbytes==0.39.0
- git+https://github.com/huggingface/transformers.git
resources:
  accelerator: A10G
  cpu: '3'
  memory: 14Gi
  use_gpu: true
runtime:
  predict_concurrency: 1
secrets: {}
spec_version: '2.0'
system_packages: []
train:
  resources:
    accelerator: null
    cpu: 500m
    memory: 512Mi
    use_gpu: false
  training_class_filename: train.py
  training_class_name: Train
  training_module_dir: train
  variables: {}
