#! /usr/bin/bash
set -e

image="saladtechnologies/comfyui"
usage="Usage: ./build --comfy <comfy-version> --api <api-version> [--devel] [--image <image> default: $image] [--push]"

cuda_base="runtime"
while [ "$1" != "" ]; do
  case $1 in
  --comfy)
    shift
    comfy_version=$1
    ;;
  --api)
    shift
    api_version=$1
    ;;
  --image)
    shift
    image=$1
    ;;
  --push)
    push=true
    ;;
  --devel)
    cuda_base="devel"
    ;;
  *)
    echo $usage
    exit 1
    ;;
  esac
  shift
done

if [ -z "$comfy_version" ] || [ -z "$api_version" ]; then
  echo $usage
  exit 1
fi

tag="comfy$comfy_version-api$api_version-base"
if [ "$cuda_base" = "devel" ]; then
  tag="$tag-devel"
fi

echo "Building $image:$tag"
docker build -t $image:$tag \
  --build-arg cuda_base=$cuda_base \
  --build-arg comfy_version=$comfy_version \
  --build-arg api_version=$api_version \
  .

if [ "$push" = true ]; then
  docker push $image:$tag
fi