FROM ghcr.io/huggingface/text-generation-inference:3.3.0

# We previously downloaded the model files using the `download-model` script.
COPY models/qwen25vl7bi/*.json /model/
COPY models/qwen25vl7bi/*.txt /model/
COPY models/qwen25vl7bi/model-00001-of-00005.safetensors /model/
COPY models/qwen25vl7bi/model-00002-of-00005.safetensors /model/
COPY models/qwen25vl7bi/model-00003-of-00005.safetensors /model/
COPY models/qwen25vl7bi/model-00004-of-00005.safetensors /model/
COPY models/qwen25vl7bi/model-00005-of-00005.safetensors /model/

ENV MODEL_ID="/model"

# Since we'll be including images in the payload, we want to set a higher payload limit.
ENV PAYLOAD_LIMIT=10000000