FROM ghcr.io/huggingface/text-generation-inference:3.3.0

COPY models/llama3211bvi/LICENSE.txt /model/
COPY models/llama3211bvi/*.json /model/
COPY models/llama3211bvi/model-00001-of-00005.safetensors /model/
COPY models/llama3211bvi/model-00002-of-00005.safetensors /model/
COPY models/llama3211bvi/model-00003-of-00005.safetensors /model/
COPY models/llama3211bvi/model-00004-of-00005.safetensors /model/
COPY models/llama3211bvi/model-00005-of-00005.safetensors /model/

ENV MODEL_ID="/model"