bundled_packages_dir: packages
data_dir: data
description: Transcribe audio files across multiple languages.
environment_variables: {}
examples_filename: examples.yaml
input_type: Any
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata:
  pretty_name: Whisper
  avatar_url: https://cdn.baseten.co/production/static/openai.png
  cover_image_url: https://cdn.baseten.co/production/static/whisper.png
  tags:
  - speech-recognition
model_module_dir: model
model_name: Whisper
model_type: custom
python_version: py39
requirements:
- git+https://github.com/openai/whisper.git
- --extra-index-url https://download.pytorch.org/whl/cu113
- requests
resources:
  cpu: 500m
  memory: 3Gi
  use_gpu: true
  accelerator: A10G
secrets: {}
spec_version: 2.0
system_packages:
- ffmpeg
external_data:
  - url: https://baseten-public.s3.us-west-2.amazonaws.com/models/whisper/small.pt
    local_data_path: models/small.pt
