#! /usr/bin/bash
set -e

usage="Usage: ./build --comfy <comfy-version> --api <api-version> [--push]"

push=""
while [ "$1" != "" ]; do
  case $1 in
  --comfy)
    shift
    comfy_version=$1
    ;;
  --api)
    shift
    api_version=$1
    ;;

  --push)
    push="--push"
    ;;
  *)
    echo $usage
    exit 1
    ;;
  esac
  shift
done

if [ -z "$comfy_version" ] || [ -z "$api_version" ]; then
  echo $usage
  exit 1
fi

function buildDirectory() {
  docker system prune -f
  pushd $1
  echo "Building $1"
  ./build --comfy $comfy_version --api $api_version $push
  popd
}

# buildDirectory comfyui-base
# buildDirectory dreamshaper8-comfyui
# buildDirectory flux1-schnell-fp8-comfyui
buildDirectory sd3.5-large-comfyui
buildDirectory sd3.5-medium-comfyui
buildDirectory sdxl-with-refiner-comfyui
