#! /usr/bin/bash
set -e

usage="Usage: ./build --comfy <comfy-version> --api <api-version> [--push]"

push=""
while [ "$1" != "" ]; do
  case $1 in
  --comfy)
    shift
    comfy_version=$1
    ;;
  --api)
    shift
    api_version=$1
    ;;

  --push)
    push="--push"
    ;;
  *)
    echo $usage
    exit 1
    ;;
  esac
  shift
done

if [ -z "$comfy_version" ] || [ -z "$api_version" ]; then
  echo $usage
  exit 1
fi

# Build the base image
pushd comfyui-base
./build --comfy $comfy_version --api $api_version $push
popd

# Build the dreamshaper8 image
pushd dreamshaper8-comfyui
./build --comfy $comfy_version --api $api_version $push
popd

# Build the flux1-schnell-fp8 image
pushd flux1-schnell-fp8-comfyui
./build --comfy $comfy_version --api $api_version $push
popd

# Build the sdxl-with-refiner image
pushd sdxl-with-refiner-comfyui
./build --comfy $comfy_version --api $api_version $push
popd