#! /usr/bin/bash


image="saladtechnologies/comfyui"
usage="Usage: ./run --comfy <comfy-version> --api <api-version> --torch <torch-version> --cuda <cuda-version> [--image <image> default: $image]"

model_name="flux1-schnell-fp8"
while [ "$1" != "" ]; do
  case $1 in
  --comfy)
    shift
    comfy_version=$1
    ;;
  --api)
    shift
    api_version=$1
    ;;
  --torch)
    shift
    torch_version=$1
    ;;
  --cuda)
    shift
    cuda_version=$1
    ;;
  --image)
    shift
    image=$1
    ;;
  *)
    echo $usage
    exit 1
    ;;
  esac
  shift
done

if [ -z "$comfy_version" ] || [ -z "$api_version" ] || [ -z "$torch_version" ] || [ -z "$cuda_version" ]; then
  echo $usage
  exit 1
fi

tag="comfy$comfy_version-api$api_version-torch$torch_version-cuda$cuda_version-$model_name"

docker run -it --rm --gpus all \
-p 8188:8188 \
-p 3000:3000 \
--name comfyui-$model_name \
$image:$tag