name: Build & publish gpt2 recipe
on:
  push:
    path:
      - '!**'
      - '/src/gpt2/*'
  # release:
  #   types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  build-truss:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write
      actions: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/docker-recipe
        with:
          recipe-name: gpt2
          version: "0.2"
          repo-token: ${{ secrets.GITHUB_TOKEN }}