name: Build & publish all recipe images
on:
  [push]
  # release:
  #   types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  build-truss:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/docker-recipe@master
        with:
          recipe-name: gpt2
          version: "0.1"

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/truss-event@master
        with:
          recipe-name: anything4.0
          version: "0.4"
