name: Build & publish all recipe images
on:
  [push]
  # release:
  #   types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  build-truss:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write
      actions: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/docker-recipe
        with:
          recipe-name: gpt2
          version: "0.1"

  build-docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write
      actions: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/truss-event
        with:
          recipe-name: anything4.0
          version: "0.4"
